sudo: false
language: node_js
node_js: "8"
cache:
  yarn: true
  directories:
  - node_modules
env:
  matrix:
  - CMD=build
  - CMD=test
  - CMD=lint
script:
- npm run $CMD
after_success:
- '[ "$CMD" == "test" ] && npm run coverage'
notifications:
  email: false
  slack:
    secure: FpWloFDhvq0CIWmFCjE4rriC3nVtUzKMBVAzLrWUpM1SfRGKfJctQ8UnmG9pUY6JFzFKYjAtTTvGKEcMAz5Pi355B10OMxuBjGkLNzgdEnw5d0yZ5EDXLsPsv0kGteHwpKlzSbPT7dxXSFifhw6x8nUdw6iDI+6Qw4sVfg8SVwoE6pPz7GTKhlt3W7Jg6JtqR+L7zRWxHE8CJkHK4q9Kfd/4YjC4OYhrjBBIyKKfBiJVbR7jIEr7BZq/Kk07mrAAaOKCaqXgHwC0TG6lZ7+GTLY8cXcA4rGB+2TClIl0UwMUtpBlSHDzRO+JSF2L3AyythbnciyJ3RWbb/vOvozqRjR1zMkIvlnSAQFC5Crh10YoF/PAYe1fJRihsFyIisTpmTfoBgd3S7LnWfRIL/n0ILY2g+e6N4NZy4tkDLowx8tA5y5K1UNIfqSR61Kc65GiAWEkbYOzrCo1bej80Ri16f4PdiZly7HRCoAudutd17M2ZRkT9BQcKB0t7ZSEeXn5odq82BKChcWpQUZQP4ycCOaZF9QffaoD7bEpVYk3joTk25ubnIAYOp/7yEeZU1jMzV8LioMKtTeRiv0xTJa5mibuSzbcwu/++gGctLgDM89I3mh3IZYaCmGVS3gnRbpczqY4h7Y8AwbeubZvCAygkxbR2bRApwlLJz2yp9aZZvM=
